twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['base_form.html.twig']
    debug: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/emails/css': email_css
        '%kernel.project_dir%/emails/template': email_template
when@test:
    twig:
        strict_variables: true
